import enum


class RoleName(str, enum.Enum):
    ADMIN = "ADMIN"
    PUBLISHER = "PUBLISHER"


class Platform(str, enum.Enum):
    FACEBOOK = "FACEBOOK"
    INSTAGRAM = "INSTAGRAM"
    LINKEDIN = "LINKEDIN"
    TWITTER = "TWITTER"
    YOUTUBE = "YOUTUBE"
    THREADS = "THREADS"
    TIKTOK = "TIKTOK"
    PINTEREST = "PINTEREST"


class PostStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    PARTIALLY_PUBLISHED = "PARTIALLY_PUBLISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PlatformContentStatus(str, enum.Enum):
    PENDING = "PENDING"
    GENERATED = "GENERATED"
    EDITED = "EDITED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"


class SocialAccountStatus(str, enum.Enum):
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    ERROR = "ERROR"


class TokenStatus(str, enum.Enum):
    VALID = "VALID"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class PublishingJobStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"


class NotificationType(str, enum.Enum):
    CONTENT_GENERATED = "CONTENT_GENERATED"
    SCHEDULED = "SCHEDULED"
    PUBLISHED = "PUBLISHED"
    PUBLISH_FAILED = "PUBLISH_FAILED"


class AuditAction(str, enum.Enum):
    USER_CREATED = "USER_CREATED"
    POST_CREATED = "POST_CREATED"
    AI_GENERATED = "AI_GENERATED"
    POST_EDITED = "POST_EDITED"
    POST_DELETED = "POST_DELETED"
    SCHEDULED = "SCHEDULED"
    PUBLISH_STARTED = "PUBLISH_STARTED"
    PUBLISH_SUCCESS = "PUBLISH_SUCCESS"
    PUBLISH_FAILED = "PUBLISH_FAILED"
    SOCIAL_ACCOUNT_CONNECTED = "SOCIAL_ACCOUNT_CONNECTED"
    SOCIAL_ACCOUNT_DISCONNECTED = "SOCIAL_ACCOUNT_DISCONNECTED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
